- name: Redmineディレクトリ以下のオーナーを変更
  sudo: yes
  command:
    chown -R {{ redmine_user }}:{{ redmine_group }} {{ redmine_dir }}

- name: Passengerをインストール
  gem: name=passenger state=present executable=~/.rbenv/shims/gem user_install=no
  register: passenger_gem_result

- name: PassengerのApache用モジュールのインストール
  command:
    ~/.rbenv/shims/passenger-install-apache2-module -a --languages 'ruby'
  when: passenger_gem_result|changed

- name: PassengerのApache用モジュールの設定を取得
  command:
    ~/.rbenv/shims/passenger-install-apache2-module --snippet
  register:
    passenger_snippet_vars
  when: passenger_gem_result|changed

- name: redmine.confの作成
  sudo: yes
  template:
    src=redmine.conf
    dest=/etc/httpd/conf.d/redmine.conf
  when: passenger_gem_result|changed
  notify: restart httpd

- name: Redmineに /redmine でアクセスするためのシンボリックリンク作成
  sudo: yes
  file:
    state=link
    src={{ redmine_dir }}/public
    dest=/var/www/html/redmine

